### ISSUE TITLE
workflow builds are failing while trying to install libffi6

### ISSUE THREAD

**Issue by sameer-j** [sujaykundu777/jekyll-deploy-action#1]
![image](https://user-images.githubusercontent.com/2439128/129944116-25534af2-8fff-4e2a-8d17-e73698aac779.png)

libffi6 is not available in https://packages.ubuntu.com/ any more. Can we move to libffi7?

**Comment by sujaykundu777** [comment]
upgraded to libffi7 @sameer-j
